### ISSUE TITLE
Add a dropcap style

### ISSUE THREAD

**Issue by hobbes7878** [The-Politico/generator-politico-interactives#15]
```css
 .dropcap {
     float: left;
     font-size: 90px;
     line-height: 0.85em;
     font-family: $tablet;
     margin-right: 0.115em;
     color: #000;
     text-transform: uppercase;
     margin-top: 0px;
 }
```
