### ISSUE TITLE
Icon fonts CORS

### ISSUE THREAD

**Issue by hobbes7878** [The-Politico/generator-politico-interactives#20]
Getting some strange CORS cross origin access errors when pulling icon fonts from absolute URLs. Not sure why, but the relative paths seem to work. Solution for now is to let relative path-based font family fall through to absolute (which we need for development).

```CSS
@font-face {
  font-family: 'base-icons';
  src: url('http://www.politico.com/fonts/website/shared/base-icons/base-icons.eot');
  src: url('http://www.politico.com/fonts/website/shared/base-icons/base-icons.eot?#iefix') format('embedded-opentype'), url('http://www.politico.com/fonts/website/shared/base-icons/base-icons.woff2') format('woff2'), url('http://www.politico.com/fonts/website/shared/base-icons/base-icons.woff') format('woff'), url('http://www.politico.com/fonts/website/shared/base-icons/base-icons.ttf') format('truetype'), url('http://www.politico.com/fonts/website/shared/base-icons/base-icons.svg#core-icons') format('svg');
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: 'base-icons-relative-path';
  src: url('/fonts/website/shared/base-icons/base-icons.eot');
  src: url('/fonts/website/shared/base-icons/base-icons.eot?#iefix') format('embedded-opentype'), url('/fonts/website/shared/base-icons/base-icons.woff2') format('woff2'), url('/fonts/website/shared/base-icons/base-icons.woff') format('woff'), url('/fonts/website/shared/base-icons/base-icons.ttf') format('truetype'), url('/fonts/website/shared/base-icons/base-icons.svg#core-icons') format('svg');
  font-weight: normal;
  font-style: normal;
}

.icon {
    font-family:  'base-icons-relative-path', 'base-icons';
    speak: none;
    font-style: normal;
    font-weight: normal;
    font-variant: normal;
    text-transform: none;
    line-height: 1;
}
```
