### ISSUE TITLE
Pym.js height on embeds not calc-d correctly

### ISSUE THREAD

**Issue by hobbes7878** [The-Politico/generator-politico-interactives#3]
Add this style rule for embeds:

```CSS
body {
  &:before,
  &:after {
    content: " ";
    display: table;
  }
}
```
